### ISSUE TITLE
在启动hoshinobot时出现报错：[WinError 3] 系统找不到指定的路径。

### ISSUE THREAD

**Issue by TeoZler** [azmiao/uma_plugin#11]
使用系统：Windows10
使用python版本：3.8.3

> C:\Users\******\Downloads\HoshinoBot>python run.py
msgpack not installed, MsgPackSerializer unavailable
[2022-03-31 16:05:28,726 config] WARNING: Not found config of "uma_plugin"
[2022-03-31 16:05:28,726 config] WARNING: Not found config of "botmanage"
[2022-03-31 16:05:28,726 config] INFO: Succeeded to load config of "groupmaster"
[2022-03-31 16:05:29,812 nonebot] ERROR: Failed to import "hoshino.modules.uma_plugin.umamusume_news", error: [WinError 3] 系统找不到指定的路径。: './res/img\\umamusume_news'
[2022-03-31 16:05:29,812 nonebot] ERROR: [WinError 3] 系统找不到指定的路径。: './res/img\\umamusume_news'
Traceback (most recent call last):
  File "C:\Users\******\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 253, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\******\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\******\Downloads\HoshinoBot\hoshino\modules\uma_plugin\umamusume_news\__init__.py", line 25, in <module>
    os.mkdir(R.img('umamusume_news').path)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: './res/img\\umamusume_news'
[2022-03-31 16:05:29,858 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_almanac"
[2022-03-31 16:05:30,798 nonebot] ERROR: Failed to import "hoshino.modules.uma_plugin.uma_comic", error: list.remove(x): x not in list
[2022-03-31 16:05:30,816 nonebot] ERROR: list.remove(x): x not in list
Traceback (most recent call last):
  File "C:\Users\******\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 253, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\******\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\******\Downloads\HoshinoBot\hoshino\modules\uma_plugin\uma_comic\__init__.py", line 12, in <module>
    loop.run_until_complete(update_info())
  File "C:\Users\******\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\******\Downloads\HoshinoBot\hoshino\modules\uma_plugin\uma_comic\comic.py", line 13, in update_info
    img_dict = await get_imgurl()
  File "C:\Users\******\Downloads\HoshinoBot\hoshino\modules\uma_plugin\uma_comic\comic.py", line 31, in get_imgurl
    en_name = await get_en_name(img_name)
  File "C:\Users\******\Downloads\HoshinoBot\hoshino\modules\uma_plugin\uma_comic\comic.py", line 70, in get_en_name
    name_list.remove('current_chara')
ValueError: list.remove(x): x not in list
[2022-03-31 16:05:30,816 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_compatibility"
[2022-03-31 16:05:30,830 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_endurance"
[2022-03-31 16:05:31,612 nonebot] ERROR: Failed to import "hoshino.modules.uma_plugin.uma_face", error: [WinError 3] 系 统找不到指定的路径。: './res/img\\uma_face'
[2022-03-31 16:05:31,612 nonebot] ERROR: [WinError 3] 系统找不到指定的路径。: './res/img\\uma_face'
Traceback (most recent call last):
  File "C:\Users\******\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 253, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\******\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\******\Downloads\HoshinoBot\hoshino\modules\uma_plugin\uma_face\__init__.py", line 13, in <module>
    loop.run_until_complete(update_info())
  File "C:\Users\******\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\******\Downloads\HoshinoBot\hoshino\modules\uma_plugin\uma_face\face.py", line 14, in update_info
    await download_img(img_id, img_dict[img_id]['url'])
  File "C:\Users\******\Downloads\HoshinoBot\hoshino\modules\uma_plugin\uma_face\face.py", line 50, in download_img
    os.mkdir(img_path)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: './res/img\\uma_face'
[2022-03-31 16:05:31,723 nonebot] ERROR: Failed to import "hoshino.modules.uma_plugin.uma_gacha", error: [WinError 3] 系统找不到指定的路径。: './res/img\\uma_gacha'
[2022-03-31 16:05:31,723 nonebot] ERROR: [WinError 3] 系统找不到指定的路径。: './res/img\\uma_gacha'
Traceback (most recent call last):
  File "C:\Users\******\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 253, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\******\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\******\Downloads\HoshinoBot\hoshino\modules\uma_plugin\uma_gacha\__init__.py", line 1, in <module>
    from .pretty_handle import update_pretty_info, pretty_draw, reload_pretty_pool, get_gacha_pool
  File "C:\Users\******\Downloads\HoshinoBot\hoshino\modules\uma_plugin\uma_gacha\pretty_handle.py", line 4, in <module>
    from .announcement import PrettyAnnouncement
  File "C:\Users\******\Downloads\HoshinoBot\hoshino\modules\uma_plugin\uma_gacha\announcement.py", line 8, in <module>
    from .config import DRAW_PATH
  File "C:\Users\******\Downloads\HoshinoBot\hoshino\modules\uma_plugin\uma_gacha\config.py", line 14, in <module>
    os.mkdir(f'{DRAW_PATH}')
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: './res/img\\uma_gacha'
[2022-03-31 16:05:31,736 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_info"
[2022-03-31 16:05:31,736 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_support_chart"
[2022-03-31 16:05:31,736 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.alert"
[2022-03-31 16:05:31,736 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.billing"
[2022-03-31 16:05:31,736 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.broadcast"
[2022-03-31 16:05:31,736 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.data_cleaner"
[2022-03-31 16:05:31,751 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.feedback"
[2022-03-31 16:05:31,751 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.get_cqcode"
[2022-03-31 16:05:31,751 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.group_invite"
[2022-03-31 16:05:31,751 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.group_leave"
[2022-03-31 16:05:31,751 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.help"
[2022-03-31 16:05:31,751 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.ls"
[2022-03-31 16:05:31,751 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.service_manage"
[2022-03-31 16:05:31,769 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.antiqks"
[2022-03-31 16:05:31,769 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.anti_abuse"
[2022-03-31 16:05:31,769 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.anti_asoul"
[2022-03-31 16:05:31,769 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.anti_holo"
[2022-03-31 16:05:31,769 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.anti_lex"
[2022-03-31 16:05:31,782 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.anti_msg_recall"
[2022-03-31 16:05:31,782 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.chat"
[2022-03-31 16:05:31,782 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.group_notice"
[2022-03-31 16:05:31,782 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.join_approve"
[2022-03-31 16:05:31,782 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.random_repeater"
[2022-03-31 16:05:31,782 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.sleeping_set"
[2022-03-31 16:05:31,782 nonebot] INFO: Running on 127.0.0.1:8080
 Serving Quart app ''
 Environment: production
 Please use an ASGI server (e.g. Hypercorn) directly in production
 Debug mode: False
 Running on http://127.0.0.1:8080 (CTRL + C to quit)
[2022-03-31 16:05:31,798 nonebot] INFO: Scheduler started
[2022-03-31 16:05:31,798] Running on http://127.0.0.1:8080 (CTRL + C to quit)
[2022-03-31 16:05:33,258] 127.0.0.1:61255 GET /ws 1.1 101 - 0

**Comment by azmiao** [comment]
请自己前往Hoshinobot文件夹下创建res文件夹，然后在res文件夹里再创建img文件夹
