### ISSUE TITLE
速卡节奏榜报错相关

### ISSUE THREAD

**Issue by GudaTom** [azmiao/uma_plugin#13]
INFO: Self: 493817083, Message 482527598 from 85443461@[群:636862882]: '速卡节奏榜'
[2022-04-11 08:47:40,539 uma_support_chart] INFO: Message 482527598 triggered SSR_speed_chart.
[2022-04-11 08:47:41,446 hoshino] INFO: 速卡节奏榜没有更新，将发送本地图片文件
[2022-04-11 08:47:41,446 hoshino] INFO: 本地速卡节奏榜图片文件丢失，正在重新合成
[2022-04-11 08:47:41,446 uma_support_chart] ERROR: <class 'UnboundLocalError'> occured when SSR_speed_chart handling message 482527598.
[2022-04-11 08:47:41,446 uma_support_chart] ERROR: local variable 'all_width' referenced before assignment
Traceback (most recent call last):
  File "C:\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_support_chart\__init__.py", line 36, in SSR_speed_chart
    msg = await generate_img(sup_type)
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_support_chart\get_url.py", line 175, in generate_img
    end_img = await fix_img(img_dict, sup_type)
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_support_chart\get_url.py", line 149, in fix_img
    end_img = Image.new('RGB', (all_width, all_height))
UnboundLocalError: local variable 'all_width' referenced before assignment
[2022-04-11 08:47:41,462 nonebot] INFO: Message 482527598 is ignored: Handled by Hoshino

**Comment by azmiao** [comment]
请问能否截图一下res/img/umamusume/uma_support_chart/下的图片文件列表呢

**Comment by GudaTom** [comment]
确实没有速度0.0，应该用什么命令重新下载图片

**Comment by azmiao** [comment]
> 确实没有速度0.0，应该用什么命令重新下载图片

这样，虽然不知道为啥会这样，你打开插件目录，uma_plugin/uma_support_chart/sup_config.json把关于速卡的那一整块删了，然后不用重启hoshino直接再发“速卡节奏榜”

**Comment by azmiao** [comment]
理论上这种情况是不可能发生的2333，我待会研究研究原因

**Comment by GudaTom** [comment]
OK，问题解决了，大佬牛逼。不过我没动过这些图片，估计是之前版本的报错导致的？

**Comment by azmiao** [comment]
> OK，问题解决了，大佬牛逼。不过我没动过这些图片，估计是之前版本的报错导致的？

俺也不知道hhh，待会我排查排查看看
