### ISSUE TITLE
依赖需要添加：ModuleNotFoundError: No module named 'prettytable'

### ISSUE THREAD

**Issue by YuanHaoReginald** [azmiao/uma_plugin#15]
[v1.6](https://github.com/azmiao/uma_plugin/commit/50d3be0320d58475b424e60f248b177bee1106a3) 的提交中，`uma_tasks/generate.py` 文件中使用了 `prettytable` 包，但是没有在 `requirements.txt` 中添加。

这导致启动的时候 `uma_tasks` 没有被启用，报错：

> [2022-04-21 16:56:33,591 nonebot] ERROR: No module named 'prettytable'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin.py", line 253, in load_plugin
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<path>/hoshino/modules/uma_plugin/uma_tasks/__init__.py", line 7, in <module>
    from .generate import get_title, get_task_info
  File "<path>/hoshino/modules/uma_plugin/uma_tasks/generate.py", line 1, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'

重新安装 `requirements.txt` 错误依然存在，`pip install PrettyTable` 后错误消失。

**Comment by azmiao** [comment]
哦对，忘了

**Comment by GudaTom** [comment]
哈哈哈，我也在寻思怎么这个uma_tasks一直没启动，原来是这个原因
