### ISSUE TITLE
大佬，救！gitpull之后也更新了依赖也删了apikey，甚至重新下了整个umaplugin也没用2333

### ISSUE THREAD

**Issue by GudaTom** [azmiao/uma_plugin#17]
PS C:\HoshinoBot> .\运行.ps1
msgpack not installed, MsgPackSerializer unavailable
[2022-04-26 16:42:05,348 config] WARNING: Not found config of "uma_plugin"
[2022-04-26 16:42:05,348 config] WARNING: Not found config of "github_reminder"
[2022-04-26 16:42:05,348 config] INFO: Succeeded to load config of "groupmaster"
[2022-04-26 16:42:05,348 config] WARNING: Not found config of "botmanage"
[2022-04-26 16:42:06,442 nonebot] ERROR: Failed to import and load "hoshino.modules.uma_plugin.umamusume_news", error: F
ailed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

[2022-04-26 16:42:06,442 nonebot] ERROR: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\git\__init__.py", line 87, in <m
odule>
    refresh()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\git\__init__.py", line 76, in re
fresh
    if not Git.refresh(path=path):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\git\cmd.py", line 341, in refres
h
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in
 _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_mo
dule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\__init__.py", line 10, in <module>
    from .uma_info.update_init import update as info_update, update_info_auto as info_auto
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_info\__init__.py", line 5, in <module>
    from .spider import uma_update
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_info\spider.py", line 4, in <module>
    from git.repo import Repo
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\git\__init__.py", line 89, in <m
odule>
    raise ImportError('Failed to initialize: {0}'.format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

[2022-04-26 16:42:06,583 nonebot] ERROR: Failed to import and load "hoshino.modules.uma_plugin.uma_almanac", error: No m
odule named 'fuzzywuzzy'
[2022-04-26 16:42:06,583 nonebot] ERROR: No module named 'fuzzywuzzy'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in
 _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_mo
dule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\__init__.py", line 11, in <module>
    from .uma_skills.update_init import update as skills_update, auto_update as skills_auto
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_skills\__init__.py", line 6, in <module>
    from .generate import get_skill_list, get_skill_info
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_skills\generate.py", line 4, in <module>
    from fuzzywuzzy import process
ModuleNotFoundError: No module named 'fuzzywuzzy'
[2022-04-26 16:42:06,583 nonebot] INFO: Succeeded to import and load "hoshino.modules.uma_plugin.uma_comic"
[2022-04-26 16:42:06,583 nonebot] INFO: Succeeded to import and load "hoshino.modules.uma_plugin.uma_compatibility"
[2022-04-26 16:42:06,583 nonebot] ERROR: Failed to import and load "hoshino.modules.uma_plugin.uma_endurance", error: No
 module named 'fuzzywuzzy'
[2022-04-26 16:42:06,583 nonebot] ERROR: No module named 'fuzzywuzzy'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in
 _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_mo
dule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\__init__.py", line 11, in <module>
    from .uma_skills.update_init import update as skills_update, auto_update as skills_auto
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_skills\__init__.py", line 6, in <module>
    from .generate import get_skill_list, get_skill_info
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_skills\generate.py", line 4, in <module>
    from fuzzywuzzy import process
ModuleNotFoundError: No module named 'fuzzywuzzy'
[2022-04-26 16:42:06,598 nonebot] INFO: Succeeded to import and load "hoshino.modules.uma_plugin.uma_face"
[2022-04-26 16:42:06,598 nonebot] ERROR: Failed to import and load "hoshino.modules.uma_plugin.uma_gacha", error: No mod
ule named 'fuzzywuzzy'
[2022-04-26 16:42:06,598 nonebot] ERROR: No module named 'fuzzywuzzy'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in
 _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_mo
dule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\__init__.py", line 11, in <module>
    from .uma_skills.update_init import update as skills_update, auto_update as skills_auto
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_skills\__init__.py", line 6, in <module>
    from .generate import get_skill_list, get_skill_info
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_skills\generate.py", line 4, in <module>
    from fuzzywuzzy import process
ModuleNotFoundError: No module named 'fuzzywuzzy'
[2022-04-26 16:42:06,598 nonebot] INFO: Succeeded to import and load "hoshino.modules.uma_plugin.uma_info"
[2022-04-26 16:42:06,598 nonebot] ERROR: Failed to import and load "hoshino.modules.uma_plugin.uma_skills", error: No mo
dule named 'fuzzywuzzy'
[2022-04-26 16:42:06,598 nonebot] ERROR: No module named 'fuzzywuzzy'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in
 _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_mo
dule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\__init__.py", line 11, in <module>
    from .uma_skills.update_init import update as skills_update, auto_update as skills_auto
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_skills\__init__.py", line 6, in <module>
    from .generate import get_skill_list, get_skill_info
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_skills\generate.py", line 4, in <module>
    from fuzzywuzzy import process
ModuleNotFoundError: No module named 'fuzzywuzzy'
[2022-04-26 16:42:06,598 nonebot] ERROR: Failed to import and load "hoshino.modules.uma_plugin.uma_support_chart", error
: No module named 'fuzzywuzzy'
[2022-04-26 16:42:06,598 nonebot] ERROR: No module named 'fuzzywuzzy'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in
 _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_mo
dule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\__init__.py", line 11, in <module>
    from .uma_skills.update_init import update as skills_update, auto_update as skills_auto
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_skills\__init__.py", line 6, in <module>
    from .generate import get_skill_list, get_skill_info
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_skills\generate.py", line 4, in <module>
    from fuzzywuzzy import process
ModuleNotFoundError: No module named 'fuzzywuzzy'
[2022-04-26 16:42:06,598 nonebot] ERROR: Failed to import and load "hoshino.modules.uma_plugin.uma_tasks", error: No mod
ule named 'fuzzywuzzy'
[2022-04-26 16:42:06,614 nonebot] ERROR: No module named 'fuzzywuzzy'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in
 _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_mo
dule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\__init__.py", line 11, in <module>
    from .uma_skills.update_init import update as skills_update, auto_update as skills_auto
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_skills\__init__.py", line 6, in <module>
    from .generate import get_skill_list, get_skill_info
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_skills\generate.py", line 4, in <module>
    from fuzzywuzzy import process
ModuleNotFoundError: No module named 'fuzzywuzzy'
[2022-04-26 16:42:06,692 nonebot] INFO: Succeeded to import and load "hoshino.modules.github_reminder.com_poller"
[2022-04-26 16:42:06,692 nonebot] INFO: Succeeded to import and load "hoshino.modules.github_reminder.get_com"
[2022-04-26 16:42:06,692 nonebot] INFO: Succeeded to import and load "hoshino.modules.github_reminder.watch"
[2022-04-26 16:42:06,692 nonebot] INFO: Succeeded to import and load "hoshino.modules.groupmaster.chat"
[2022-04-26 16:42:06,692 nonebot] INFO: Succeeded to import and load "hoshino.modules.groupmaster.group_notice"
[2022-04-26 16:42:06,692 nonebot] INFO: Succeeded to import and load "hoshino.modules.groupmaster.join_approve"
[2022-04-26 16:42:06,692 nonebot] INFO: Succeeded to import and load "hoshino.modules.groupmaster.random_repeater"
[2022-04-26 16:42:06,692 nonebot] INFO: Succeeded to import and load "hoshino.modules.botmanage.alert"
[2022-04-26 16:42:06,692 nonebot] INFO: Succeeded to import and load "hoshino.modules.botmanage.broadcast"
[2022-04-26 16:42:06,692 nonebot] INFO: Succeeded to import and load "hoshino.modules.botmanage.data_cleaner"
[2022-04-26 16:42:06,708 nonebot] INFO: Succeeded to import and load "hoshino.modules.botmanage.get_cqcode"
[2022-04-26 16:42:06,708 nonebot] INFO: Succeeded to import and load "hoshino.modules.botmanage.group_invite"
[2022-04-26 16:42:06,708 nonebot] INFO: Succeeded to import and load "hoshino.modules.botmanage.group_leave"
[2022-04-26 16:42:06,708 nonebot] INFO: Succeeded to import and load "hoshino.modules.botmanage.help"
[2022-04-26 16:42:06,708 nonebot] INFO: Succeeded to import and load "hoshino.modules.botmanage.ls"
[2022-04-26 16:42:06,708 nonebot] INFO: Succeeded to import and load "hoshino.modules.botmanage.service_manage"
C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\message.py:58: UserWarning: defi
ning message_preprocessor outside a plugin is deprecated and will not be supported in the future
  warnings.warn('defining message_preprocessor outside a plugin is deprecated '
[2022-04-26 16:42:06,708 nonebot] INFO: Running on 127.0.0.1:2333
 * Serving Quart app ''
 * Environment: production
 * Please use an ASGI server (e.g. Hypercorn) directly in production
 * Debug mode: False
 * Running on http://127.0.0.1:2333 (CTRL + C to quit)
[2022-04-26 16:42:06,708 nonebot] INFO: Scheduler started
[2022-04-26 16:42:06,708] Running on http://127.0.0.1:2333 (CTRL + C to quit)
[2022-04-26 16:42:08,133] 127.0.0.1:52555 GET /ws/ 1.1 101 - 0

**Comment by CYDXDianXian** [comment]
```
pip install fuzzywuzzy
```
缺少了依赖，安装一下，估计是阿梓喵忘了更新requirements了

**Comment by azmiao** [comment]
同上，不过因为hoshino原版里也需要这个库，所以我就没在里面写2333，我一会补上吧

**Comment by GudaTom** [comment]
ERROR: Failed to import and load "hoshino.modules.uma_plugin.umamusume_news", error: F
ailed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
- be included in your $PATH
- be set via $GIT_PYTHON_GIT_EXECUTABLE
- explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
- quiet|q|silence|s|none|n|0: for no warning or exception
- warn|w|warning|1: for a printed warning
- error|e|raise|r|2: for a raised exception

Example:
export GIT_PYTHON_REFRESH=quiet

收到~已安装依赖，那这种错误怎么解决~~

**Comment by azmiao** [comment]
> uma_plugin.umamusume_news

可否看一下你的目录uma_plugin/umamusume_news
另外，这个问题我也不是很清楚但貌似是gitpython库的问题，话说你有安装git bash软件吗

**Comment by CYDXDianXian** [comment]
错误原因： 无法找到git.exe
解决办法：寻找git.exe, 然后给git.exe 添加环境变量，重启电脑
寻找git——打开git-bash , 输入where git  
![image](https://user-images.githubusercontent.com/71607036/165267547-3b5559b0-9928-4a21-93ef-084e7f894c3b.png)
添加为环境变量
![image](https://user-images.githubusercontent.com/71607036/165267407-bfb81c26-10b9-4c85-b82f-76aad0b59f7b.png)
重启电脑生效-不重启可能不生效

**Comment by GudaTom** [comment]
有安装的，我更新都是打开git bash 然后git pull的，我咋记得傻瓜教程里有设置过环境变量，我去搞搞，谢谢大佬们

**Comment by azmiao** [comment]
> 有安装的，我更新都是打开git bash 然后git pull的，我咋记得傻瓜教程里有设置过环境变量，我去搞搞，谢谢大佬们

所以现在咋样了嘞

**Comment by GudaTom** [comment]
> > 有安装的，我更新都是打开git bash 然后git pull的，我咋记得傻瓜教程里有设置过环境变量，我去搞搞，谢谢大佬们
> 
> 所以现在咋样了嘞

应该是我没有用git引进项目的问题，这种下载文件的我也是第一次见到会报错。回家搞个梯子重新弄一下应该就可以了，继续上班！

**Comment by azmiao** [comment]
> > > 有安装的，我更新都是打开git bash 然后git pull的，我咋记得傻瓜教程里有设置过环境变量，我去搞搞，谢谢大佬们
> > 
> > 
> > 所以现在咋样了嘞
> 
> 应该是我没有用git引进项目的问题，这种下载文件的我也是第一次见到会报错。回家搞个梯子重新弄一下应该就可以了，继续上班！

好，那issue我先关闭了。如果还有问题你再开本issue吧
