### ISSUE TITLE
作者大大我又来啦，第一个错是启动时的，第二个错是找不到节奏榜的那个config

### ISSUE THREAD

**Issue by GudaTom** [azmiao/uma_plugin#19]
PS C:\HoshinoBot> .\运行.ps1
msgpack not installed, MsgPackSerializer unavailable
[2022-05-05 09:17:25,075 config] WARNING: Not found config of "botmanage"
[2022-05-05 09:17:25,075 config] INFO: Succeeded to load config of "groupmaster"
[2022-05-05 09:17:25,075 config] WARNING: Not found config of "uma_plugin"
[2022-05-05 09:17:26,394 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.alert"
[2022-05-05 09:17:26,394 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.broadcast"
[2022-05-05 09:17:26,394 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.data_cleaner"
[2022-05-05 09:17:26,394 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.get_cqcode"
[2022-05-05 09:17:26,394 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.group_invite"
[2022-05-05 09:17:26,394 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.group_leave"
[2022-05-05 09:17:26,425 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.help"
[2022-05-05 09:17:26,425 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.ls"
[2022-05-05 09:17:26,425 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.service_manage"
[2022-05-05 09:17:26,441 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.chat"
[2022-05-05 09:17:26,441 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.group_notice"
[2022-05-05 09:17:26,441 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.join_approve"
[2022-05-05 09:17:26,441 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.random_repeater"
C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Usin
g slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
[2022-05-05 09:17:27,400 hoshino] INFO: ====未检测到马娘漫画信息，正在开始更新====
[2022-05-05 09:17:27,790 nonebot] ERROR: Failed to import "hoshino.modules.uma_plugin.umamusume_news", error: list.remov
e(x): x not in list
[2022-05-05 09:17:27,790 nonebot] ERROR: list.remove(x): x not in list
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 263, in
 load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_mo
dule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\__init__.py", line 75, in <module>
    loop.run_until_complete(update())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_unti
l_complete
    return future.result()
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\__init__.py", line 60, in update
    await comic_update()
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_comic\update_init.py", line 12, in update
    await update_info()
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_comic\comic.py", line 13, in update_info
    img_dict = await get_imgurl()
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_comic\comic.py", line 31, in get_imgurl
    en_name = await get_en_name(img_name)
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_comic\comic.py", line 70, in get_en_name
    name_list.remove('current_chara')
ValueError: list.remove(x): x not in list
[2022-05-05 09:17:27,806 nonebot] ERROR: Failed to import "hoshino.modules.uma_plugin.uma_almanac", error: Service name
"uma_help" already exist!
[2022-05-05 09:17:27,806 nonebot] ERROR: Service name "uma_help" already exist!
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 263, in
 load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_mo
dule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\__init__.py", line 34, in <module>
    sv = Service('uma_help', help_ = sv_help)
  File "C:\HoshinoBot\hoshino\service.py", line 128, in __init__
    assert self.name not in _loaded_services, f'Service name "{self.name}" already exist!'
AssertionError: Service name "uma_help" already exist!
[2022-05-05 09:17:27,806 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_comic"
[2022-05-05 09:17:27,806 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_compatibility"
[2022-05-05 09:17:27,806 nonebot] ERROR: Failed to import "hoshino.modules.uma_plugin.uma_endurance", error: Service nam
e "uma_help" already exist!
[2022-05-05 09:17:27,806 nonebot] ERROR: Service name "uma_help" already exist!
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 263, in
 load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_mo
dule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\__init__.py", line 34, in <module>
    sv = Service('uma_help', help_ = sv_help)
  File "C:\HoshinoBot\hoshino\service.py", line 128, in __init__
    assert self.name not in _loaded_services, f'Service name "{self.name}" already exist!'
AssertionError: Service name "uma_help" already exist!
[2022-05-05 09:17:27,806 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_face"
[2022-05-05 09:17:27,806 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_gacha"
[2022-05-05 09:17:27,806 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_info"
[2022-05-05 09:17:27,806 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_skills"
[2022-05-05 09:17:27,806 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_support_chart"
[2022-05-05 09:17:27,806 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_tasks"
[2022-05-05 09:17:27,822 nonebot] INFO: Running on 127.0.0.1:2333
 * Serving Quart app ''
 * Environment: production
 * Please use an ASGI server (e.g. Hypercorn) directly in production
 * Debug mode: False
 * Running on http://127.0.0.1:2333 (CTRL + C to quit)
[2022-05-05 09:17:27,822 nonebot] INFO: Scheduler started
[2022-05-05 09:17:27,822] Running on http://127.0.0.1:2333 (CTRL + C to quit)
[2022-05-05 09:17:56,106] 127.0.0.1:49986 GET /ws/ 1.1 101 - 0
[2022-05-05 09:17:56,111 nonebot] INFO: Self: 493817083, Message -183698802 from 1840683454@[群:636862882]: '根卡节奏榜'
[2022-05-05 09:17:56,111 nonebot] INFO: Self: 493817083, Message -2113156584 from 85443461@[群:636862882]: '手动更新马娘
数据'
[2022-05-05 09:17:56,111 uma_support_chart] INFO: Message -183698802 triggered SSR_speed_chart.
[2022-05-05 09:17:56,111 uma_support_chart] ERROR: <class 'FileNotFoundError'> occured when SSR_speed_chart handling mes
sage -183698802.
[2022-05-05 09:17:56,111 uma_support_chart] ERROR: [Errno 2] No such file or directory: 'C:\\HoshinoBot\\hoshino\\module
s\\uma_plugin\\uma_support_chart\\sup_config.json'
Traceback (most recent call last):
  File "C:\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_support_chart\__init__.py", line 25, in SSR_speed_chart
    msg = await generate_img(sup_type)
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_support_chart\get_url.py", line 170, in generate_img
    img_dict, is_update = await generate_url(sup_type)
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_support_chart\get_url.py", line 33, in generate_url
    with open(current_dir, 'r', encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\HoshinoBot\\hoshino\\modules\\uma_plugin\\uma_support_chart
\\sup_config.json'
[2022-05-05 09:18:05,574 uma_info] INFO: Message -2113156584 triggered update_info.
[2022-05-05 09:18:05,574 hoshino] INFO: 正在更新数据至最新，请耐心等待，预计用时1分钟
[2022-05-05 09:18:05,574 nonebot] INFO: Message -183698802 is ignored: Handled by Hoshino
[2022-05-05 09:18:05,848 nonebot] INFO: Message -2113156584 is ignored: Handled by Hoshino
[2022-05-05 09:27:26,330 nonebot] INFO: Self: 493817083, Message 1802006317 from 85443461@[群:636862882]: '[CQ:image,fil

**Comment by azmiao** [comment]
没有config都是首次启动时没有生成，请检查一下这个目录文件`C:\HoshinoBot\hoshino\modules\uma_plugin_init.py`，你的日志里有这个东西，但实际不应该有`uma_plugin_init.py`文件，这个是啥我也不知道，请确保modeles文件夹下只有文件夹

**Comment by GudaTom** [comment]
之前我留了个备份文件夹在那，原来不能放在那里。但是我删了之后还是有个错，要不作者大大帮忙上服务器看一眼，这个错我纠结了1个星期了，一直没弄好2333 有木有qq群啥的，我私聊给你服务器

**Comment by azmiao** [comment]
> 之前我留了个备份文件夹在那，原来不能放在那里。但是我删了之后还是有个错，要不作者大大帮忙上服务器看一眼，这个错我纠结了1个星期了，一直没弄好2333 有木有qq群啥的，我私聊给你服务器

别，这容易出事，不放心，你截图发日志

**Comment by GudaTom** [comment]
PS C:\HoshinoBot> .\运行.ps1
msgpack not installed, MsgPackSerializer unavailable
[2022-05-05 10:03:22,420 config] INFO: Succeeded to load config of "groupmaster"
[2022-05-05 10:03:22,420 config] WARNING: Not found config of "uma_plugin"
[2022-05-05 10:03:22,420 config] WARNING: Not found config of "botmanage"
[2022-05-05 10:03:23,407 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.chat"
[2022-05-05 10:03:23,407 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.group_notice"
[2022-05-05 10:03:23,407 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.join_approve"
[2022-05-05 10:03:23,423 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.random_repeater"
C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Usin
g slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
[2022-05-05 10:03:24,222 hoshino] INFO: ====未检测到马娘漫画信息，正在开始更新====
[2022-05-05 10:03:24,597 nonebot] ERROR: Failed to import "hoshino.modules.uma_plugin.umamusume_news", error: list.remov
e(x): x not in list
[2022-05-05 10:03:24,597 nonebot] ERROR: list.remove(x): x not in list
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 263, in
 load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_mo
dule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\__init__.py", line 75, in <module>
    loop.run_until_complete(update())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_unti
l_complete
    return future.result()
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\__init__.py", line 60, in update
    await comic_update()
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_comic\update_init.py", line 12, in update
    await update_info()
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_comic\comic.py", line 13, in update_info
    img_dict = await get_imgurl()
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_comic\comic.py", line 31, in get_imgurl
    en_name = await get_en_name(img_name)
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\uma_comic\comic.py", line 70, in get_en_name
    name_list.remove('current_chara')
ValueError: list.remove(x): x not in list
[2022-05-05 10:03:24,597 nonebot] ERROR: Failed to import "hoshino.modules.uma_plugin.uma_almanac", error: Service name
"uma_help" already exist!
[2022-05-05 10:03:24,597 nonebot] ERROR: Service name "uma_help" already exist!
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 263, in
 load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_mo
dule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\__init__.py", line 34, in <module>
    sv = Service('uma_help', help_ = sv_help)
  File "C:\HoshinoBot\hoshino\service.py", line 128, in __init__
    assert self.name not in _loaded_services, f'Service name "{self.name}" already exist!'
AssertionError: Service name "uma_help" already exist!
[2022-05-05 10:03:24,597 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_comic"
[2022-05-05 10:03:24,597 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_compatibility"
[2022-05-05 10:03:24,597 nonebot] ERROR: Failed to import "hoshino.modules.uma_plugin.uma_endurance", error: Service nam
e "uma_help" already exist!
[2022-05-05 10:03:24,597 nonebot] ERROR: Service name "uma_help" already exist!
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 263, in
 load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_mo
dule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\HoshinoBot\hoshino\modules\uma_plugin\__init__.py", line 34, in <module>
    sv = Service('uma_help', help_ = sv_help)
  File "C:\HoshinoBot\hoshino\service.py", line 128, in __init__
    assert self.name not in _loaded_services, f'Service name "{self.name}" already exist!'
AssertionError: Service name "uma_help" already exist!

**Comment by azmiao** [comment]
Service name "uma_help" already exist!，这是你有服务冲突了，你是不是还有备份的残留着，有一说一，如果你没有其他需要备份的插件的话，建议直接把整个Hoshinobot文件夹删了重新装一下Hoshino

**Comment by GudaTom** [comment]
是啊，我就是顶不住全部删了，然后去小白教程重新搞了一遍。uma_plugin也是重新git下载下来的。

**Comment by azmiao** [comment]
你把你的modules文件夹下面所有东西截图一份看看

**Comment by GudaTom** [comment]
![image](https://user-images.githubusercontent.com/40374414/166855081-7235c3d5-24b9-4af1-be05-9c4e207b7fb9.png)
![image](https://user-images.githubusercontent.com/40374414/166855097-4fde4d01-014a-4f76-bd77-c297c7ae381b.png)
![image](https://user-images.githubusercontent.com/40374414/166855105-b9c1c6bc-44a6-4806-b4d9-c90a87e65e5a.png)
![image](https://user-images.githubusercontent.com/40374414/166855112-f5b8d6cf-b27a-4b94-8b4b-a9811e97bf02.png)

**Comment by GudaTom** [comment]
哦，我知道了，日啊！是之前git的环境变量没配置好的情况下，我跑了一遍然后报错了（上一个issue没看清大佬的回答，环境变量调错了把bin写成了bin\git.exe），调好了之后再也跑不起来了。要把整个HoshinoBot删了重装再跑。

**Comment by azmiao** [comment]
> ![image](https://user-images.githubusercontent.com/40374414/166855081-7235c3d5-24b9-4af1-be05-9c4e207b7fb9.png) ![image](https://user-images.githubusercontent.com/40374414/166855097-4fde4d01-014a-4f76-bd77-c297c7ae381b.png) ![image](https://user-images.githubusercontent.com/40374414/166855105-b9c1c6bc-44a6-4806-b4d9-c90a87e65e5a.png) ![image](https://user-images.githubusercontent.com/40374414/166855112-f5b8d6cf-b27a-4b94-8b4b-a9811e97bf02.png)

有一说一，挺正常的（，稍等我研究研究

**Comment by GudaTom** [comment]
![image](https://user-images.githubusercontent.com/40374414/166855318-f053b309-a112-4dc7-b220-276b62f3c8ca.png)
xz现在看起来正常了

**Comment by azmiao** [comment]
> ![image](https://user-images.githubusercontent.com/40374414/166855318-f053b309-a112-4dc7-b220-276b62f3c8ca.png) xz现在看起来正常了

啊这，这样就对了

**Comment by GudaTom** [comment]
太折磨辣，呜呜呜。这鬼错误恶心了我一周

**Comment by azmiao** [comment]
我一会把教程里的版本也更新到最新吧，防止再出问题

**Comment by GudaTom** [comment]
> 我一会把教程里的版本也更新到最新吧，防止再出问题

辛苦了，作者大大，作者大大最棒了！！！

**Comment by azmiao** [comment]
哦，大概知道了，上面这些错误应该是第一次更新出错了，但没有出错的文件夹和文件没有删除，导致再次启动的时候无法成功更新，马上修

**Comment by GudaTom** [comment]
> 哦，大概知道了，上面这些错误应该是第一次更新出错了，但没有出错的文件夹和文件没有删除，导致再次启动的时候无法成功更新，马上修

对，就是这么个意思，作者大大赛高~！越来越健壮了
