### ISSUE TITLE
相性，决胜服等功能报错

### ISSUE THREAD

**Issue by chenchenriver** [azmiao/uma_plugin#5]
[2022-03-09 15:54:50,520 nonebot] INFO: Self: 1287795651, Message -613179396 from 584801993@[群:321385678]: '查角色决胜服 米浴'
[2022-03-09 15:54:50,521 uma_info] INFO: Message -613179396 triggered get_single_info.
[2022-03-09 15:54:50,521 uma_info] ERROR: <class 'FileNotFoundError'> occured when get_single_info handling message -613179396.
[2022-03-09 15:54:50,521 uma_info] ERROR: [Errno 2] No such file or directory: '/root/HoshinoBot/hoshino/modules/uma_plugin/uma_info/config.json'
Traceback (most recent call last):
  File "/root/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/root/HoshinoBot/hoshino/modules/uma_plugin/uma_info/__init__.py", line 159, in get_single_info
    with open(current_dir, 'r', encoding = 'UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/HoshinoBot/hoshino/modules/uma_plugin/uma_info/config.json'

**Comment by chenchenriver** [comment]
api已经申请和填写
![image](https://user-images.githubusercontent.com/93070768/157397379-5f1fbaac-6d10-4232-9ee2-22be2531997e.png)

**Comment by azmiao** [comment]
哦我的上帝，是Linux，我这没适配Linux 233333

**Comment by azmiao** [comment]
一会我尽量改改让他同时兼容linux和winserver吧

**Comment by chenchenriver** [comment]
好的，非常感谢

**Comment by azmiao** [comment]
欸，不对啊，我用的也是os.path应该是linux winserver通用的吧，你截图看看uma_info文件夹下？

**Comment by chenchenriver** [comment]
![image](https://user-images.githubusercontent.com/93070768/157400944-9a451d78-f719-4d96-b68b-ef1eae34a28f.png)

**Comment by azmiao** [comment]
你这个是因为没有使用命令：“手动更新马娘数据” 导致的，你去随便找个群发一句这个就行，后台会更新基础数据的，由于启动时自动检测马娘抽卡数据是否存在并更新了，就没有弄检测基础数据并更新了

**Comment by chenchenriver** [comment]
好的谢谢，正在更新，更新完成后给您反馈

**Comment by chenchenriver** [comment]
没有问题了，谢谢！

**Comment by azmiao** [comment]
好嘞
