### ISSUE TITLE
不能手动更新马娘数据

### ISSUE THREAD

**Issue by 0bug0** [azmiao/uma_plugin#9]
[2022-03-23 03:35:42,606 uma_info] INFO: Message 296829842 triggered update_info.
[2022-03-23 03:35:42,606 uma_info] INFO: 本地配置文件不存在，正在开始创建
[2022-03-23 03:35:42,606 uma_info] INFO: 本地配置文件创建完成，开始更新数据库数据
[2022-03-23 03:35:47,711 uma_info] ERROR: <class 'aiocqhttp.exceptions.ActionFailed'> occured when update_info handling message 296829842.
[2022-03-23 03:35:47,711 uma_info] ERROR: <ActionFailed data=None, echo={'seq': 1}, msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出'>
Traceback (most recent call last):
  File "/root/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/root/HoshinoBot/hoshino/service.py", line 224, in wrapper
    return await func(bot, event)
  File "/root/HoshinoBot/hoshino/modules/uma_plugin/uma_info/__init__.py", line 292, in update_info
    await bot.send(ev, msg)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 271, in send
    return await self.send_msg(**params)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 238, in call_action
    return await self._api.call_action(action=action, **params)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 178, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 153, in call_action
    return _handle_api_result(await
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 38, in _handle_api_result
    raise ActionFailed(result=result)
aiocqhttp.exceptions.ActionFailed: <ActionFailed data=None, echo={'seq': 1}, msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出'>
大佬能不能帮忙看看

**Comment by azmiao** [comment]
你在报错这一段的时候看看go-cqhttp的日志

**Comment by 0bug0** [comment]
整个文件都是
连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused
找的我好辛苦，报错那段显示是账号可能被风控，但我这个小号很久以前的了，而且文字那些也能正常发送

**Comment by azmiao** [comment]
> 

显示风控那就是风控了，一般recode100都是风控，另外链接到ws失败说明你根本没有链接到go-cqhttp，请先链接上在测试

**Comment by 0bug0** [comment]
重新检查了一下
[WARNING]: 群消息发送失败: 账号可能被风控.
[WARNING]: 警告: 长消息延迟为 3154ms, 大于 1000ms, 可能导致无法接收/发送长消息的情况, 请检查本地网络状态.
[WARNING]: 警告: 长消息响应延迟为 15264ms, 大于 1000ms, 可能导致无法接收/发送长消息的情况, 请检查本地网络状态.

**Comment by azmiao** [comment]
> 

这里应该没有长消息，大概就是风控了，一个字：寄

**Comment by 0bug0** [comment]
好的吧，先谢谢大佬了。之后遇到其他问题再反馈了
